name: '🚀 Feature Request'
description: 'I have a suggestion 😻!'
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        ## :warning: We use GitHub Issues to track bug reports, feature requests and regressions

        If you are not sure that your issue is a bug, you could:

        - use our [Discord community](https://discord.gg/624YFphcKp)
        - use [StackOverflow using the tag `mantis-cli`](https://stackoverflow.com/questions/tagged/mantis-cli)

        ---

  - type: checkboxes
    attributes:
      label: 'Is there an existing issue that is already proposing this?'
      description: 'Please [search for existing issues](./?q=is%3Aissue) to see if one already exists for the feature you are requesting'
      options:
        - label: 'I have searched the existing issues'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Is your feature request related to a problem? Please describe it'
      description: 'A clear and concise description of what the problem is'
      placeholder: |
        I have an issue when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen. Add any considered drawbacks'

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'What is the motivation / use case for changing the behavior?'
      description: 'Describe the motivation or the concrete use case'
