name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: restore dependencies
        uses: bahmutov/npm-install@v1
      - run: npm run lint:all
  type_check:
    name: type check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: restore dependencies
        uses: bahmutov/npm-install@v1
      - run: npm run type-check
